# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
# rn_path = '../node_modules/react-native'
rn_path = '/usr/local/lib/node_modules/react-native'

target 'RCTTxim' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RCTTxim
  pod 'React', :path => rn_path, :subspecs => [
    'Core',
    'DevSupport',
  ]
  pod 'yoga', :path => rn_path + '/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => rn_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => rn_path + '/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => rn_path + '/third-party-podspecs/glog.podspec'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
end
